//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeInventarioInformatico
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialCambios
    {
        public int idHistorialCambio { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEquipo { get; set; }
        public int idTipoCambio { get; set; }
    
        public virtual cambioTipos cambioTipos { get; set; }
        public virtual equipos equipos { get; set; }
    }
}
