//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeInventarioInformatico
{
    using System;
    using System.Collections.Generic;
    
    public partial class perifericos
    {
        public int idPeriferico { get; set; }
        public System.DateTime fecCompra { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> garantia { get; set; }
        public int estado { get; set; }
        public string modelo { get; set; }
        public Nullable<int> idEquipo { get; set; }
        public string caracteristicas { get; set; }
        public int idTipoPeriferico { get; set; }
        public int idMarca { get; set; }
        public int idProveedor { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual tipoPerifericos tipoPerifericos { get; set; }
    }
}
